### ISSUE TITLE
Darc Installation Issue

### ISSUE THREAD

**Issue by kailash011** [JarryShaw/darc#19]
I am trying to install darc using pip install python-darc but getting error and installation failing. Please find attached file for more details.

![image](https://user-images.githubusercontent.com/14266252/91888877-95cc2180-ecaa-11ea-8080-52f801554d24.png)

**Comment by JarryShaw** [comment]
thx for using `darc` @kailash011 but before i worked out a fix for this issue, pls find two possible workarounds as below:

1.  upgrade to Python 3.8
   darc` was developed and battle-field tested on Python 3.8; i cannot guarantee if it works smoothly on older version of Python

2. install `python-walrus` first then install `python-darc`
   `darc` uses `walrus` to backport assignment expressions; it seems that the postinstall hook i made is not working as expected; so, just install `walrus` ahead of `darc` so that the postinstall process can successfully proceed

**Comment by kailash011** [comment]
Thnx for your help, the issue has been resolved by installing python3.8
